stages:
  - init
  - test
  - build
  - run

before_script:
  - export GOROOT="/opt/go"
  - export GOPATH="/home/gitlab-runner/go"
  - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

copy_dir:
  stage: init
  script:
    - gmake copy_dir

unit_tests:
  stage: test
  script:
    - gmake test

race_detector:
  stage: test
  script:
    - gmake race

code_coverage:
  stage: test
  script:
    - gmake coverage
#  only:
#  - master

go_report:
  stage: test
  script:
    - gmake goreport
#  only:
#  - master

#lint_code:
#  stage: test
#  script:
#    - gmake lint_dep
#    - gmake lint

build:
  stage: build
  script:
    - gmake
    - sudo /usr/sbin/service clarinet stop
    - sudo cp $PWD/clarinet /bin/clarinet
    - sudo chmod 755 /bin/clarinet
    - sudo /usr/sbin/service clarinet start
    - echo "Finished"
#  only:
#  - master
